edited index.html and App.js.
BitByte-TPC/TPC-website pull request #10
Opened 2021-01-07 16:51 UTC by abhineetpandey10

2021-01-08 08:25 UTC, abhineetpandey10 commented
https://user-images.githubusercontent.com/54185164/103991661-020ae480-51b9-11eb-9941-e58e13c60007.mp4

The webpage UI is now responsive.

2021-01-08 09:00 UTC, Samy-33 requested changes

2021-01-08 09:00 UTC, Samy-33 commented on frontend/src/App.js
> +function App()
leave a blank line between imports and function

2021-01-08 09:00 UTC, Samy-33 commented
@abhineetpandey10, how is it responsive when there is a horizontal scroll bar?

2021-01-08 10:07 UTC, abhineetpandey10 commented
I had misinterpreted "**Responsive**". Have edited the comment accordingly, and have applied the requested changes in the "App.js" file.

2021-01-08 10:19 UTC, Samy-33 commented
> I had misinterpreted "**Responsive**". Have edited the comment accordingly, and have applied the requested changes in the "App.js" file.

No problem. Please read below about how to write good commit messages:
https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

2021-01-14 09:19 UTC, MananJethwani commented
this PR needs to be closed sorry @abhineetpandey10 aksh has already made most of the component and that will me merged soon and that includes correct fonts responsive site and mobile view as well extremly sorry for wasting your time

2021-01-14 09:19 UTC, closed without merging