#issue 32 resolved Responsiveness of home page
BitByte-TPC/TPC-website pull request #43
Opened 2022-05-30 17:19 UTC by Rahul-Palahwat

**Issue Number 32**

fixes #
I have changed the font size to 3 rem when our media query fires at 1180 px and added one media query to handle the overlapping 
Some screenshots are attached below:
<img width="1440" alt="Screenshot 2022-05-30 at 10 30 34 PM" src="https://user-images.githubusercontent.com/72152598/171037469-4b0e2725-729e-40f9-a27d-b1746455554d.png">

<img width="1440" alt="Screenshot 2022-05-30 at 10 42 20 PM" src="https://user-images.githubusercontent.com/72152598/171037474-b31f9143-ba63-44cc-80c3-b3c1568f8cfb.png">

<img width="1440" alt="Screenshot 2022-05-30 at 10 42 24 PM" src="https://user-images.githubusercontent.com/72152598/171037479-c3a1357f-dfa3-439f-bddf-9facd2984acb.png">

**Checklist**

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route

<!-- Please add deployed link to here text >

2022-05-30 17:44 UTC, Rahul19241 commented
@garg3133 please review this PR

2022-05-30 17:53 UTC, Samy-33 commented
@Rahul19241, you can request for review at the top right corner:
![image](https://user-images.githubusercontent.com/15676805/171041033-ddcc4d57-5cb7-411b-b8e7-7e7a23cbfb20.png)

Please do it for all your PRs.

2022-05-30 17:58 UTC, Aksh-Bansal-dev requested changes
Looks good. Just need a few changes.

Change the commit messages to follow commit guidelines as mentioned in the [CONTRIBUTING.md](https://github.com/BitByte-TPC/TPC-website/blob/main/CONTRIBUTING.md#standard-commit-messages).

2022-05-30 17:58 UTC, Aksh-Bansal-dev commented on frontend/src/components/WhyUs/style.module.css
> +    /* padding-top: 20vh; */
Remove commented code.

2022-05-30 17:58 UTC, Aksh-Bansal-dev commented on frontend/src/pages/homePage/style.module.css
> +
Remove this empty line.

2022-05-30 18:03 UTC, Rahul-Palahwat commented on frontend/src/components/WhyUs/style.module.css
> +    /* padding-top: 20vh; */
done

2022-05-30 18:03 UTC, Rahul19241 commented on frontend/src/pages/homePage/style.module.css
> +
done

2022-05-30 18:04 UTC, Rahul19241 commented
@Aksh-Bansal-dev done with all changes. Please go through once

2022-05-30 18:06 UTC, Aksh-Bansal-dev commented
> Change the commit messages to follow commit guidelines as mentioned in the [CONTRIBUTING.md](https://github.com/BitByte-TPC/TPC-website/blob/main/CONTRIBUTING.md#standard-commit-messages).

Also, squash all commits into a single commit.

2022-06-11 10:20 UTC, Rahul-Palahwat commented
@Aksh-Bansal-dev sorry for inactive on this pr, can u please help me in squashing all commits in a single commit

2022-06-11 11:18 UTC, Aksh-Bansal-dev commented
Use `git rebase -i` and squash them into a single commit.
[Tutorial](https://www.git-tower.com/learn/git/faq/git-squash).

2022-06-11 12:49 UTC, Rahul-Palahwat commented
@Aksh-Bansal-dev sir as i have changed the username of my github account so i am facing the problem that i am not able to   squash the code....sir can i generate a new PR which will follow guidelines as in contributing.md

2022-06-11 15:49 UTC, Aksh-Bansal-dev commented
> sir can i generate a new PR which will follow guidelines as in contributing.md

Yeah, I am closing this PR then.

2022-06-11 15:49 UTC, closed without merging