home page reactjs initial commit
BitByte-TPC/TPC-website pull request #8
Opened 2020-12-28 10:58 UTC by Aksh-Bansal-dev

![Screenshot (20)](https://user-images.githubusercontent.com/63552235/103209645-99567900-4929-11eb-9b38-3ed8df5f6ac7.png)

2020-12-29 12:50 UTC, MananJethwani requested changes
aksh looks like this is not responsive can you please make it responsive using flexbox

2021-01-12 12:15 UTC, Aksh-Bansal-dev commented
![Screenshot (24)](https://user-images.githubusercontent.com/63552235/104313352-e75ca680-54fd-11eb-8c28-1929052d4775.png)
![Screenshot (25)](https://user-images.githubusercontent.com/63552235/104313357-e9bf0080-54fd-11eb-8a3f-1bb2a380364f.png)

2021-01-14 10:09 UTC, MananJethwani approved these changes
correct the indentation and squash commits into one so that I can push it into main code

2021-01-14 10:09 UTC, MananJethwani commented on frontend/src/App.js
> +import Nav from "./components/Nav";
@Aksh-Bansal-dev this should be "./components/nav" right?

2021-01-14 10:09 UTC, MananJethwani commented on frontend/src/components/homeNav/index.jsx
> +        <span className={styles.navBtn}>About Us</span>
correct the indentation here

2021-01-14 10:09 UTC, MananJethwani commented on frontend/src/components/shortcuts/index.jsx
> +        <a href="https://www.github.com"><img className={styles.logo}  src="./ComponentTMP_0-image2.png" alt="github"/></a>
indentation here

2021-01-14 10:09 UTC, MananJethwani commented on frontend/src/components/svgbackground/index.js
> +        <path id="Intersection_1" data-name="Intersection 1" d="M279.111,1207.79C322.137,1073.069,399.415,672.667,49.8,130.906V128.79H881.989l.811,24.761V1207.79Z" transform="translate(-49.8 -128.79)
indentation here

2021-01-14 10:14 UTC, merged